# Rust formatting configuration for The Pattern

# Basic formatting
edition = "2021"
hard_tabs = false
tab_spaces = 4
max_width = 100

# Alignment and spacing
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 80

# Strings
format_strings = true
format_macro_matchers = true

# Structure
use_field_init_shorthand = true
use_try_shorthand = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# Control flow
control_brace_style = "AlwaysSameLine"
brace_style = "SameLineWhere"
trailing_comma = "Vertical"
trailing_semicolon = true

# Functions
fn_params_layout = "Tall"
fn_args_layout = "Tall"

# Matches
match_block_trailing_comma = true
match_arm_leading_pipes = "Never"

# Chains
chain_width = 80
single_line_if_else_max_width = 80

# Spaces
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false

# Experimental features (nightly)
# unstable_features = true
# format_code_in_doc_comments = true
# normalize_doc_attributes = true